version: 2

sources:
  - name: SALES_DATA
    database: DBT_DB
    schema: DBT_RAW_SCHEMA
    tables:
      - name: CUSTOMER
      - name: LINEITEM
      - name: NATION
      - name: ORDERS
      - name: PART
      - name: PARTSUPP
      - name: REGION
      - name: SUPPLIER
